// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEn6GDp3gFOGdx0n-m4NQbYQUHHh0GPN8',
    appId: '1:646154546893:web:e35004f638008100854384',
    messagingSenderId: '646154546893',
    projectId: 'saloon-app-mane',
    authDomain: 'saloon-app-mane.firebaseapp.com',
    databaseURL: 'https://saloon-app-mane-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'saloon-app-mane.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL06dK2qNCnD1vwibeYZ8VM1sWMsX4PaU',
    appId: '1:646154546893:android:6ef3bb0c0f805457854384',
    messagingSenderId: '646154546893',
    projectId: 'saloon-app-mane',
    databaseURL: 'https://saloon-app-mane-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'saloon-app-mane.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNcxbVR41KRCf3sklbaJd_dJf9ZkZlVrc',
    appId: '1:646154546893:ios:7ca3fb5ac0e44dd9854384',
    messagingSenderId: '646154546893',
    projectId: 'saloon-app-mane',
    databaseURL: 'https://saloon-app-mane-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'saloon-app-mane.appspot.com',
    iosBundleId: 'com.example.mane',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNcxbVR41KRCf3sklbaJd_dJf9ZkZlVrc',
    appId: '1:646154546893:ios:7ca3fb5ac0e44dd9854384',
    messagingSenderId: '646154546893',
    projectId: 'saloon-app-mane',
    databaseURL: 'https://saloon-app-mane-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'saloon-app-mane.appspot.com',
    iosBundleId: 'com.example.mane',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEn6GDp3gFOGdx0n-m4NQbYQUHHh0GPN8',
    appId: '1:646154546893:web:2d66b60325d2d8f5854384',
    messagingSenderId: '646154546893',
    projectId: 'saloon-app-mane',
    authDomain: 'saloon-app-mane.firebaseapp.com',
    databaseURL: 'https://saloon-app-mane-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'saloon-app-mane.appspot.com',
  );
}
